apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: app-staging
data:
  ENV_VALUE1: ${PRODUCTION_ENV_VALUE1}
  ENV_VALUE2: ${ENV_VALUE2}

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app-production-deployment
  labels:
    app: app-production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-production
  template:
    metadata:
      labels:
        app: app-production
    spec:
      containers:
        - name: app-staging
          image: ${AWS_REPOSITORY_URL}/${REPOSITORY_NAME}:${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: app-config

---
kind: Service
apiVersion: v1
metadata:
  name: app-production-service
spec:
  type: LoadBalancer
  selector:
    app: app-production
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000